language: python
python:
    - "3.4"
script: python ./compile.py && python ./audit.py
deploy:
  skip_cleanup: true
  provider: script
  script: python deploy.py ./licenses.json
  on:
    branch: master
